#!/usr/bin/env python3
"""Check external ILBM qualification reports against a committed JSON manifest.

Manifest format: {"samples": [{"id": "...", "sha256": "64 hex chars",
"source_url": "https://...", "report": "path/to/report.json"}]}.
Reports are generated by qualify_external_ilbm.py; binaries are not vendored.
"""
import argparse
import json
import pathlib
import re
import sys


def validate(manifest, base):
    samples = manifest.get("samples")
    if not isinstance(samples, list):
        raise ValueError("manifest.samples must be an array")
    seen = set()
    for sample in samples:
        if not isinstance(sample, dict):
            raise ValueError("sample must be an object")
        ident = sample.get("id")
        digest = sample.get("sha256")
        source = sample.get("source_url")
        report_path = sample.get("report")
        if not isinstance(ident, str) or not ident or ident in seen:
            raise ValueError("sample id missing or duplicated")
        seen.add(ident)
        if not isinstance(digest, str) or not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise ValueError(f"{ident}: invalid sha256")
        if not isinstance(source, str) or not source.startswith("https://"):
            raise ValueError(f"{ident}: source_url must use https")
        if not isinstance(report_path, str) or not report_path:
            raise ValueError(f"{ident}: missing report path")
        path = (base / report_path).resolve()
        if not path.is_relative_to(base.resolve()):
            raise ValueError(f"{ident}: report path escapes manifest directory")
        report = json.loads(path.read_text(encoding="utf-8"))
        if report.get("sha256") != digest:
            raise ValueError(f"{ident}: report digest mismatch")
        if report.get("form") != "ILBM" or not isinstance(report.get("qualified"), bool):
            raise ValueError(f"{ident}: invalid qualification report")
    return len(samples)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=pathlib.Path)
    args = parser.parse_args()
    try:
        count = validate(json.loads(args.manifest.read_text(encoding="utf-8")),
                         args.manifest.resolve().parent)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"qualification manifest invalid: {exc}", file=sys.stderr)
        return 1
    print(f"qualification manifest valid: {count} samples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
